Making the build happy and even execute tests. The tests, JUnit5 and Surefire caused:
ClassNotFoundException: javax.lang.model.element.Element

which I was not able to workaround in any other way but to downgrade the
compiler plugin to 3.5.1 and require java 8 to build stuff.